server:
   port: 50000
   servlet:
      context-path: /reactspringcontainer
spring:
   application:
      name: reactspringcontainer
                 
---

spring:
   profiles:
      active: dev
                       
---

spring:
   profiles: uat
             
---

spring:
   profiles: sit

---

spring:
   profiles: prod